INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (1, 'Ba Đình', 'Quận', 1);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (2, 'Hoàn Kiếm', 'Quận', 1);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (3, 'Tây Hồ', 'Quận', 1);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (4, 'Long Biên', 'Quận', 1);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (5, 'Cầu Giấy', 'Quận', 1);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (6, 'Đống Đa', 'Quận', 1);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (7, 'Hai Bà Trưng', 'Quận', 1);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (8, 'Hoàng Mai', 'Quận', 1);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (9, 'Thanh Xuân', 'Quận', 1);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (16, 'Sóc Sơn', 'Huyện', 1);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (17, 'Đông Anh', 'Huyện', 1);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (18, 'Gia Lâm', 'Huyện', 1);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (19, 'Nam Từ Liêm', 'Quận', 1);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (20, 'Thanh Trì', 'Huyện', 1);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (21, 'Bắc Từ Liêm', 'Quận', 1);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (250, 'Mê Linh', 'Huyện', 1);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (268, 'Hà Đông', 'Quận', 1);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (269, 'Sơn Tây', 'Thị xã', 1);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (271, 'Ba Vì', 'Huyện', 1);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (272, 'Phúc Thọ', 'Huyện', 1);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (273, 'Đan Phượng', 'Huyện', 1);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (274, 'Hoài Đức', 'Huyện', 1);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (275, 'Quốc Oai', 'Huyện', 1);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (276, 'Thạch Thất', 'Huyện', 1);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (277, 'Chương Mỹ', 'Huyện', 1);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (278, 'Thanh Oai', 'Huyện', 1);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (279, 'Thường Tín', 'Huyện', 1);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (280, 'Phú Xuyên', 'Huyện', 1);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (281, 'Ứng Hòa', 'Huyện', 1);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (282, 'Mỹ Đức', 'Huyện', 1);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (24, 'Hà Giang', 'Thành phố', 2);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (26, 'Đồng Văn', 'Huyện', 2);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (27, 'Mèo Vạc', 'Huyện', 2);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (28, 'Yên Minh', 'Huyện', 2);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (29, 'Quản Bạ', 'Huyện', 2);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (30, 'Vị Xuyên', 'Huyện', 2);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (31, 'Bắc Mê', 'Huyện', 2);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (32, 'Hoàng Su Phì', 'Huyện', 2);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (33, 'Xín Mần', 'Huyện', 2);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (34, 'Bắc Quang', 'Huyện', 2);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (35, 'Quang Bình', 'Huyện', 2);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (40, 'Cao Bằng', 'Thành phố', 4);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (42, 'Bảo Lâm', 'Huyện', 4);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (43, 'Bảo Lạc', 'Huyện', 4);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (44, 'Thông Nông', 'Huyện', 4);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (45, 'Hà Quảng', 'Huyện', 4);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (46, 'Trà Lĩnh', 'Huyện', 4);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (47, 'Trùng Khánh', 'Huyện', 4);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (48, 'Hạ Lang', 'Huyện', 4);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (49, 'Quảng Uyên', 'Huyện', 4);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (50, 'Phục Hoà', 'Huyện', 4);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (51, 'Hoà An', 'Huyện', 4);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (52, 'Nguyên Bình', 'Huyện', 4);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (53, 'Thạch An', 'Huyện', 4);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (58, 'Bắc Kạn', 'Thành phố', 6);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (60, 'Pác Nặm', 'Huyện', 6);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (61, 'Ba Bể', 'Huyện', 6);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (62, 'Ngân Sơn', 'Huyện', 6);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (63, 'Bạch Thông', 'Huyện', 6);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (64, 'Chợ Đồn', 'Huyện', 6);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (65, 'Chợ Mới', 'Huyện', 6);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (66, 'Na Rì', 'Huyện', 6);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (70, 'Tuyên Quang', 'Thành phố', 8);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (71, 'Lâm Bình', 'Huyện', 8);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (72, 'Nà Hang', 'Huyện', 8);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (73, 'Chiêm Hóa', 'Huyện', 8);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (74, 'Hàm Yên', 'Huyện', 8);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (75, 'Yên Sơn', 'Huyện', 8);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (76, 'Sơn Dương', 'Huyện', 8);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (80, 'Lào Cai', 'Thành phố', 10);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (82, 'Bát Xát', 'Huyện', 10);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (83, 'Mường Khương', 'Huyện', 10);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (84, 'Si Ma Cai', 'Huyện', 10);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (85, 'Bắc Hà', 'Huyện', 10);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (86, 'Bảo Thắng', 'Huyện', 10);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (87, 'Bảo Yên', 'Huyện', 10);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (88, 'Sa Pa', 'Huyện', 10);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (89, 'Văn Bàn', 'Huyện', 10);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (94, 'Điện Biên Phủ', 'Thành phố', 11);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (95, 'Mường Lay', 'Thị xã', 11);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (96, 'Mường Nhé', 'Huyện', 11);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (97, 'Mường Chà', 'Huyện', 11);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (98, 'Tủa Chùa', 'Huyện', 11);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (99, 'Tuần Giáo', 'Huyện', 11);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (100, 'Điện Biên', 'Huyện', 11);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (101, 'Điện Biên Đông', 'Huyện', 11);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (102, 'Mường Ảng', 'Huyện', 11);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (103, 'Nậm Pồ', 'Huyện', 11);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (105, 'Lai Châu', 'Thành phố', 12);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (106, 'Tam Đường', 'Huyện', 12);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (107, 'Mường Tè', 'Huyện', 12);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (108, 'Sìn Hồ', 'Huyện', 12);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (109, 'Phong Thổ', 'Huyện', 12);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (110, 'Than Uyên', 'Huyện', 12);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (111, 'Tân Uyên', 'Huyện', 12);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (112, 'Nậm Nhùn', 'Huyện', 12);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (116, 'Sơn La', 'Thành phố', 14);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (118, 'Quỳnh Nhai', 'Huyện', 14);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (119, 'Thuận Châu', 'Huyện', 14);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (120, 'Mường La', 'Huyện', 14);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (121, 'Bắc Yên', 'Huyện', 14);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (122, 'Phù Yên', 'Huyện', 14);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (123, 'Mộc Châu', 'Huyện', 14);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (124, 'Yên Châu', 'Huyện', 14);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (125, 'Mai Sơn', 'Huyện', 14);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (126, 'Sông Mã', 'Huyện', 14);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (127, 'Sốp Cộp', 'Huyện', 14);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (128, 'Vân Hồ', 'Huyện', 14);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (132, 'Yên Bái', 'Thành phố', 15);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (133, 'Nghĩa Lộ', 'Thị xã', 15);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (135, 'Lục Yên', 'Huyện', 15);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (136, 'Văn Yên', 'Huyện', 15);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (137, 'Mù Căng Chải', 'Huyện', 15);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (138, 'Trấn Yên', 'Huyện', 15);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (139, 'Trạm Tấu', 'Huyện', 15);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (140, 'Văn Chấn', 'Huyện', 15);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (141, 'Yên Bình', 'Huyện', 15);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (148, 'Hòa Bình', 'Thành phố', 17);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (150, 'Đà Bắc', 'Huyện', 17);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (151, 'Kỳ Sơn', 'Huyện', 17);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (152, 'Lương Sơn', 'Huyện', 17);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (153, 'Kim Bôi', 'Huyện', 17);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (154, 'Cao Phong', 'Huyện', 17);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (155, 'Tân Lạc', 'Huyện', 17);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (156, 'Mai Châu', 'Huyện', 17);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (157, 'Lạc Sơn', 'Huyện', 17);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (158, 'Yên Thủy', 'Huyện', 17);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (159, 'Lạc Thủy', 'Huyện', 17);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (164, 'Thái Nguyên', 'Thành phố', 19);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (165, 'Sông Công', 'Thành phố', 19);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (167, 'Định Hóa', 'Huyện', 19);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (168, 'Phú Lương', 'Huyện', 19);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (169, 'Đồng Hỷ', 'Huyện', 19);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (170, 'Võ Nhai', 'Huyện', 19);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (171, 'Đại Từ', 'Huyện', 19);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (172, 'Phổ Yên', 'Thị xã', 19);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (173, 'Phú Bình', 'Huyện', 19);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (178, 'Lạng Sơn', 'Thành phố', 20);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (180, 'Tràng Định', 'Huyện', 20);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (181, 'Bình Gia', 'Huyện', 20);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (182, 'Văn Lãng', 'Huyện', 20);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (183, 'Cao Lộc', 'Huyện', 20);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (184, 'Văn Quan', 'Huyện', 20);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (185, 'Bắc Sơn', 'Huyện', 20);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (186, 'Hữu Lũng', 'Huyện', 20);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (187, 'Chi Lăng', 'Huyện', 20);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (188, 'Lộc Bình', 'Huyện', 20);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (189, 'Đình Lập', 'Huyện', 20);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (193, 'Hạ Long', 'Thành phố', 22);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (194, 'Móng Cái', 'Thành phố', 22);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (195, 'Cẩm Phả', 'Thành phố', 22);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (196, 'Uông Bí', 'Thành phố', 22);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (198, 'Bình Liêu', 'Huyện', 22);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (199, 'Tiên Yên', 'Huyện', 22);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (200, 'Đầm Hà', 'Huyện', 22);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (201, 'Hải Hà', 'Huyện', 22);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (202, 'Ba Chẽ', 'Huyện', 22);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (203, 'Vân Đồn', 'Huyện', 22);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (204, 'Hoành Bồ', 'Huyện', 22);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (205, 'Đông Triều', 'Thị xã', 22);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (206, 'Quảng Yên', 'Thị xã', 22);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (207, 'Cô Tô', 'Huyện', 22);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (213, 'Bắc Giang', 'Thành phố', 24);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (215, 'Yên Thế', 'Huyện', 24);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (216, 'Tân Yên', 'Huyện', 24);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (217, 'Lạng Giang', 'Huyện', 24);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (218, 'Lục Nam', 'Huyện', 24);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (219, 'Lục Ngạn', 'Huyện', 24);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (220, 'Sơn Động', 'Huyện', 24);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (221, 'Yên Dũng', 'Huyện', 24);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (222, 'Việt Yên', 'Huyện', 24);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (223, 'Hiệp Hòa', 'Huyện', 24);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (227, 'Việt Trì', 'Thành phố', 25);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (228, 'Phú Thọ', 'Thị xã', 25);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (230, 'Đoan Hùng', 'Huyện', 25);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (231, 'Hạ Hoà', 'Huyện', 25);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (232, 'Thanh Ba', 'Huyện', 25);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (233, 'Phù Ninh', 'Huyện', 25);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (234, 'Yên Lập', 'Huyện', 25);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (235, 'Cẩm Khê', 'Huyện', 25);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (236, 'Tam Nông', 'Huyện', 25);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (237, 'Lâm Thao', 'Huyện', 25);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (238, 'Thanh Sơn', 'Huyện', 25);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (239, 'Thanh Thuỷ', 'Huyện', 25);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (240, 'Tân Sơn', 'Huyện', 25);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (243, 'Vĩnh Yên', 'Thành phố', 26);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (244, 'Phúc Yên', 'Thị xã', 26);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (246, 'Lập Thạch', 'Huyện', 26);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (247, 'Tam Dương', 'Huyện', 26);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (248, 'Tam Đảo', 'Huyện', 26);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (249, 'Bình Xuyên', 'Huyện', 26);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (251, 'Yên Lạc', 'Huyện', 26);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (252, 'Vĩnh Tường', 'Huyện', 26);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (253, 'Sông Lô', 'Huyện', 26);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (256, 'Bắc Ninh', 'Thành phố', 27);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (258, 'Yên Phong', 'Huyện', 27);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (259, 'Quế Võ', 'Huyện', 27);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (260, 'Tiên Du', 'Huyện', 27);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (261, 'Từ Sơn', 'Thị xã', 27);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (262, 'Thuận Thành', 'Huyện', 27);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (263, 'Gia Bình', 'Huyện', 27);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (264, 'Lương Tài', 'Huyện', 27);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (288, 'Hải Dương', 'Thành phố', 30);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (290, 'Chí Linh', 'Thị xã', 30);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (291, 'Nam Sách', 'Huyện', 30);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (292, 'Kinh Môn', 'Huyện', 30);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (293, 'Kim Thành', 'Huyện', 30);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (294, 'Thanh Hà', 'Huyện', 30);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (295, 'Cẩm Giàng', 'Huyện', 30);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (296, 'Bình Giang', 'Huyện', 30);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (297, 'Gia Lộc', 'Huyện', 30);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (298, 'Tứ Kỳ', 'Huyện', 30);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (299, 'Ninh Giang', 'Huyện', 30);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (300, 'Thanh Miện', 'Huyện', 30);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (303, 'Hồng Bàng', 'Quận', 31);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (304, 'Ngô Quyền', 'Quận', 31);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (305, 'Lê Chân', 'Quận', 31);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (306, 'Hải An', 'Quận', 31);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (307, 'Kiến An', 'Quận', 31);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (308, 'Đồ Sơn', 'Quận', 31);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (309, 'Dương Kinh', 'Quận', 31);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (311, 'Thuỷ Nguyên', 'Huyện', 31);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (312, 'An Dương', 'Huyện', 31);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (313, 'An Lão', 'Huyện', 31);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (314, 'Kiến Thuỵ', 'Huyện', 31);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (315, 'Tiên Lãng', 'Huyện', 31);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (316, 'Vĩnh Bảo', 'Huyện', 31);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (317, 'Cát Hải', 'Huyện', 31);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (318, 'Bạch Long Vĩ', 'Huyện', 31);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (323, 'Hưng Yên', 'Thành phố', 33);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (325, 'Văn Lâm', 'Huyện', 33);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (326, 'Văn Giang', 'Huyện', 33);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (327, 'Yên Mỹ', 'Huyện', 33);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (328, 'Mỹ Hào', 'Huyện', 33);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (329, 'Ân Thi', 'Huyện', 33);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (330, 'Khoái Châu', 'Huyện', 33);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (331, 'Kim Động', 'Huyện', 33);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (332, 'Tiên Lữ', 'Huyện', 33);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (333, 'Phù Cừ', 'Huyện', 33);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (336, 'Thái Bình', 'Thành phố', 34);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (338, 'Quỳnh Phụ', 'Huyện', 34);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (339, 'Hưng Hà', 'Huyện', 34);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (340, 'Đông Hưng', 'Huyện', 34);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (341, 'Thái Thụy', 'Huyện', 34);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (342, 'Tiền Hải', 'Huyện', 34);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (343, 'Kiến Xương', 'Huyện', 34);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (344, 'Vũ Thư', 'Huyện', 34);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (347, 'Phủ Lý', 'Thành phố', 35);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (349, 'Duy Tiên', 'Huyện', 35);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (350, 'Kim Bảng', 'Huyện', 35);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (351, 'Thanh Liêm', 'Huyện', 35);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (352, 'Bình Lục', 'Huyện', 35);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (353, 'Lý Nhân', 'Huyện', 35);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (356, 'Nam Định', 'Thành phố', 36);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (358, 'Mỹ Lộc', 'Huyện', 36);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (359, 'Vụ Bản', 'Huyện', 36);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (360, 'Ý Yên', 'Huyện', 36);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (361, 'Nghĩa Hưng', 'Huyện', 36);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (362, 'Nam Trực', 'Huyện', 36);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (363, 'Trực Ninh', 'Huyện', 36);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (364, 'Xuân Trường', 'Huyện', 36);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (365, 'Giao Thủy', 'Huyện', 36);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (366, 'Hải Hậu', 'Huyện', 36);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (369, 'Ninh Bình', 'Thành phố', 37);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (370, 'Tam Điệp', 'Thành phố', 37);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (372, 'Nho Quan', 'Huyện', 37);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (373, 'Gia Viễn', 'Huyện', 37);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (374, 'Hoa Lư', 'Huyện', 37);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (375, 'Yên Khánh', 'Huyện', 37);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (376, 'Kim Sơn', 'Huyện', 37);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (377, 'Yên Mô', 'Huyện', 37);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (380, 'Thanh Hóa', 'Thành phố', 38);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (381, 'Bỉm Sơn', 'Thị xã', 38);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (382, 'Sầm Sơn', 'Thành phố', 38);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (384, 'Mường Lát', 'Huyện', 38);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (385, 'Quan Hóa', 'Huyện', 38);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (386, 'Bá Thước', 'Huyện', 38);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (387, 'Quan Sơn', 'Huyện', 38);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (388, 'Lang Chánh', 'Huyện', 38);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (389, 'Ngọc Lặc', 'Huyện', 38);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (390, 'Cẩm Thủy', 'Huyện', 38);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (391, 'Thạch Thành', 'Huyện', 38);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (392, 'Hà Trung', 'Huyện', 38);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (393, 'Vĩnh Lộc', 'Huyện', 38);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (394, 'Yên Định', 'Huyện', 38);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (395, 'Thọ Xuân', 'Huyện', 38);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (396, 'Thường Xuân', 'Huyện', 38);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (397, 'Triệu Sơn', 'Huyện', 38);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (398, 'Thiệu Hóa', 'Huyện', 38);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (399, 'Hoằng Hóa', 'Huyện', 38);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (400, 'Hậu Lộc', 'Huyện', 38);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (401, 'Nga Sơn', 'Huyện', 38);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (402, 'Như Xuân', 'Huyện', 38);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (403, 'Như Thanh', 'Huyện', 38);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (404, 'Nông Cống', 'Huyện', 38);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (405, 'Đông Sơn', 'Huyện', 38);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (406, 'Quảng Xương', 'Huyện', 38);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (407, 'Tĩnh Gia', 'Huyện', 38);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (412, 'Vinh', 'Thành phố', 40);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (413, 'Cửa Lò', 'Thị xã', 40);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (414, 'Thái Hoà', 'Thị xã', 40);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (415, 'Quế Phong', 'Huyện', 40);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (416, 'Quỳ Châu', 'Huyện', 40);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (417, 'Kỳ Sơn', 'Huyện', 40);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (418, 'Tương Dương', 'Huyện', 40);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (419, 'Nghĩa Đàn', 'Huyện', 40);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (420, 'Quỳ Hợp', 'Huyện', 40);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (421, 'Quỳnh Lưu', 'Huyện', 40);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (422, 'Con Cuông', 'Huyện', 40);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (423, 'Tân Kỳ', 'Huyện', 40);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (424, 'Anh Sơn', 'Huyện', 40);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (425, 'Diễn Châu', 'Huyện', 40);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (426, 'Yên Thành', 'Huyện', 40);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (427, 'Đô Lương', 'Huyện', 40);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (428, 'Thanh Chương', 'Huyện', 40);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (429, 'Nghi Lộc', 'Huyện', 40);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (430, 'Nam Đàn', 'Huyện', 40);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (431, 'Hưng Nguyên', 'Huyện', 40);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (432, 'Hoàng Mai', 'Thị xã', 40);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (436, 'Hà Tĩnh', 'Thành phố', 42);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (437, 'Hồng Lĩnh', 'Thị xã', 42);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (439, 'Hương Sơn', 'Huyện', 42);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (440, 'Đức Thọ', 'Huyện', 42);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (441, 'Vũ Quang', 'Huyện', 42);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (442, 'Nghi Xuân', 'Huyện', 42);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (443, 'Can Lộc', 'Huyện', 42);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (444, 'Hương Khê', 'Huyện', 42);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (445, 'Thạch Hà', 'Huyện', 42);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (446, 'Cẩm Xuyên', 'Huyện', 42);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (447, 'Kỳ Anh', 'Huyện', 42);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (448, 'Lộc Hà', 'Huyện', 42);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (449, 'Kỳ Anh', 'Thị xã', 42);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (450, 'Đồng Hới', 'Thành phố', 44);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (452, 'Minh Hóa', 'Huyện', 44);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (453, 'Tuyên Hóa', 'Huyện', 44);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (454, 'Quảng Trạch', 'Thị xã', 44);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (455, 'Bố Trạch', 'Huyện', 44);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (456, 'Quảng Ninh', 'Huyện', 44);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (457, 'Lệ Thủy', 'Huyện', 44);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (458, 'Ba Đồn', 'Huyện', 44);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (461, 'Đông Hà', 'Thành phố', 45);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (462, 'Quảng Trị', 'Thị xã', 45);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (464, 'Vĩnh Linh', 'Huyện', 45);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (465, 'Hướng Hóa', 'Huyện', 45);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (466, 'Gio Linh', 'Huyện', 45);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (467, 'Đa Krông', 'Huyện', 45);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (468, 'Cam Lộ', 'Huyện', 45);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (469, 'Triệu Phong', 'Huyện', 45);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (470, 'Hải Lăng', 'Huyện', 45);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (471, 'Cồn Cỏ', 'Huyện', 45);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (474, 'Huế', 'Thành phố', 46);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (476, 'Phong Điền', 'Huyện', 46);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (477, 'Quảng Điền', 'Huyện', 46);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (478, 'Phú Vang', 'Huyện', 46);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (479, 'Hương Thủy', 'Thị xã', 46);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (480, 'Hương Trà', 'Thị xã', 46);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (481, 'A Lưới', 'Huyện', 46);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (482, 'Phú Lộc', 'Huyện', 46);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (483, 'Nam Đông', 'Huyện', 46);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (490, 'Liên Chiểu', 'Quận', 48);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (491, 'Thanh Khê', 'Quận', 48);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (492, 'Hải Châu', 'Quận', 48);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (493, 'Sơn Trà', 'Quận', 48);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (494, 'Ngũ Hành Sơn', 'Quận', 48);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (495, 'Cẩm Lệ', 'Quận', 48);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (497, 'Hòa Vang', 'Huyện', 48);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (498, 'Hoàng Sa', 'Huyện', 48);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (502, 'Tam Kỳ', 'Thành phố', 49);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (503, 'Hội An', 'Thành phố', 49);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (504, 'Tây Giang', 'Huyện', 49);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (505, 'Đông Giang', 'Huyện', 49);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (506, 'Đại Lộc', 'Huyện', 49);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (507, 'Điện Bàn', 'Thị xã', 49);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (508, 'Duy Xuyên', 'Huyện', 49);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (509, 'Quế Sơn', 'Huyện', 49);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (510, 'Nam Giang', 'Huyện', 49);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (511, 'Phước Sơn', 'Huyện', 49);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (512, 'Hiệp Đức', 'Huyện', 49);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (513, 'Thăng Bình', 'Huyện', 49);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (514, 'Tiên Phước', 'Huyện', 49);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (515, 'Bắc Trà My', 'Huyện', 49);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (516, 'Nam Trà My', 'Huyện', 49);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (517, 'Núi Thành', 'Huyện', 49);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (518, 'Phú Ninh', 'Huyện', 49);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (519, 'Nông Sơn', 'Huyện', 49);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (522, 'Quảng Ngãi', 'Thành phố', 51);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (524, 'Bình Sơn', 'Huyện', 51);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (525, 'Trà Bồng', 'Huyện', 51);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (526, 'Tây Trà', 'Huyện', 51);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (527, 'Sơn Tịnh', 'Huyện', 51);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (528, 'Tư Nghĩa', 'Huyện', 51);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (529, 'Sơn Hà', 'Huyện', 51);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (530, 'Sơn Tây', 'Huyện', 51);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (531, 'Minh Long', 'Huyện', 51);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (532, 'Nghĩa Hành', 'Huyện', 51);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (533, 'Mộ Đức', 'Huyện', 51);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (534, 'Đức Phổ', 'Huyện', 51);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (535, 'Ba Tơ', 'Huyện', 51);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (536, 'Lý Sơn', 'Huyện', 51);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (540, 'Qui Nhơn', 'Thành phố', 52);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (542, 'An Lão', 'Huyện', 52);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (543, 'Hoài Nhơn', 'Huyện', 52);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (544, 'Hoài Ân', 'Huyện', 52);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (545, 'Phù Mỹ', 'Huyện', 52);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (546, 'Vĩnh Thạnh', 'Huyện', 52);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (547, 'Tây Sơn', 'Huyện', 52);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (548, 'Phù Cát', 'Huyện', 52);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (549, 'An Nhơn', 'Thị xã', 52);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (550, 'Tuy Phước', 'Huyện', 52);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (551, 'Vân Canh', 'Huyện', 52);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (555, 'Tuy Hoà', 'Thành phố', 54);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (557, 'Sông Cầu', 'Thị xã', 54);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (558, 'Đồng Xuân', 'Huyện', 54);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (559, 'Tuy An', 'Huyện', 54);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (560, 'Sơn Hòa', 'Huyện', 54);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (561, 'Sông Hinh', 'Huyện', 54);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (562, 'Tây Hoà', 'Huyện', 54);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (563, 'Phú Hoà', 'Huyện', 54);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (564, 'Đông Hòa', 'Huyện', 54);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (568, 'Nha Trang', 'Thành phố', 56);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (569, 'Cam Ranh', 'Thành phố', 56);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (570, 'Cam Lâm', 'Huyện', 56);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (571, 'Vạn Ninh', 'Huyện', 56);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (572, 'Ninh Hòa', 'Thị xã', 56);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (573, 'Khánh Vĩnh', 'Huyện', 56);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (574, 'Diên Khánh', 'Huyện', 56);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (575, 'Khánh Sơn', 'Huyện', 56);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (576, 'Trường Sa', 'Huyện', 56);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (582, 'Phan Rang-Tháp Chàm', 'Thành phố', 58);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (584, 'Bác Ái', 'Huyện', 58);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (585, 'Ninh Sơn', 'Huyện', 58);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (586, 'Ninh Hải', 'Huyện', 58);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (587, 'Ninh Phước', 'Huyện', 58);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (588, 'Thuận Bắc', 'Huyện', 58);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (589, 'Thuận Nam', 'Huyện', 58);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (593, 'Phan Thiết', 'Thành phố', 60);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (594, 'La Gi', 'Thị xã', 60);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (595, 'Tuy Phong', 'Huyện', 60);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (596, 'Bắc Bình', 'Huyện', 60);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (597, 'Hàm Thuận Bắc', 'Huyện', 60);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (598, 'Hàm Thuận Nam', 'Huyện', 60);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (599, 'Tánh Linh', 'Huyện', 60);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (600, 'Đức Linh', 'Huyện', 60);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (601, 'Hàm Tân', 'Huyện', 60);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (602, 'Phú Quí', 'Huyện', 60);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (608, 'Kon Tum', 'Thành phố', 62);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (610, 'Đắk Glei', 'Huyện', 62);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (611, 'Ngọc Hồi', 'Huyện', 62);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (612, 'Đắk Tô', 'Huyện', 62);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (613, 'Kon Plông', 'Huyện', 62);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (614, 'Kon Rẫy', 'Huyện', 62);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (615, 'Đắk Hà', 'Huyện', 62);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (616, 'Sa Thầy', 'Huyện', 62);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (617, 'Tu Mơ Rông', 'Huyện', 62);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (618, 'Ia H'' Drai', 'Huyện', 62);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (622, 'Pleiku', 'Thành phố', 64);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (623, 'An Khê', 'Thị xã', 64);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (624, 'Ayun Pa', 'Thị xã', 64);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (625, 'KBang', 'Huyện', 64);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (626, 'Đăk Đoa', 'Huyện', 64);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (627, 'Chư Păh', 'Huyện', 64);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (628, 'Ia Grai', 'Huyện', 64);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (629, 'Mang Yang', 'Huyện', 64);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (630, 'Kông Chro', 'Huyện', 64);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (631, 'Đức Cơ', 'Huyện', 64);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (632, 'Chư Prông', 'Huyện', 64);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (633, 'Chư Sê', 'Huyện', 64);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (634, 'Đăk Pơ', 'Huyện', 64);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (635, 'Ia Pa', 'Huyện', 64);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (637, 'Krông Pa', 'Huyện', 64);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (638, 'Phú Thiện', 'Huyện', 64);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (639, 'Chư Pưh', 'Huyện', 64);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (643, 'Buôn Ma Thuột', 'Thành phố', 66);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (644, 'Buôn Hồ', 'Thị xã', 66);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (645, 'Ea H''leo', 'Huyện', 66);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (646, 'Ea Súp', 'Huyện', 66);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (647, 'Buôn Đôn', 'Huyện', 66);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (648, 'Cư M''gar', 'Huyện', 66);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (649, 'Krông Búk', 'Huyện', 66);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (650, 'Krông Năng', 'Huyện', 66);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (651, 'Ea Kar', 'Huyện', 66);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (652, 'M''Đrắk', 'Huyện', 66);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (653, 'Krông Bông', 'Huyện', 66);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (654, 'Krông Pắc', 'Huyện', 66);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (655, 'Krông A Na', 'Huyện', 66);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (656, 'Lắk', 'Huyện', 66);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (657, 'Cư Kuin', 'Huyện', 66);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (660, 'Gia Nghĩa', 'Thị xã', 67);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (661, 'Đăk Glong', 'Huyện', 67);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (662, 'Cư Jút', 'Huyện', 67);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (663, 'Đắk Mil', 'Huyện', 67);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (664, 'Krông Nô', 'Huyện', 67);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (665, 'Đắk Song', 'Huyện', 67);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (666, 'Đắk R''Lấp', 'Huyện', 67);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (667, 'Tuy Đức', 'Huyện', 67);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (672, 'Đà Lạt', 'Thành phố', 68);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (673, 'Bảo Lộc', 'Thành phố', 68);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (674, 'Đam Rông', 'Huyện', 68);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (675, 'Lạc Dương', 'Huyện', 68);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (676, 'Lâm Hà', 'Huyện', 68);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (677, 'Đơn Dương', 'Huyện', 68);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (678, 'Đức Trọng', 'Huyện', 68);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (679, 'Di Linh', 'Huyện', 68);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (680, 'Bảo Lâm', 'Huyện', 68);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (681, 'Đạ Huoai', 'Huyện', 68);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (682, 'Đạ Tẻh', 'Huyện', 68);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (683, 'Cát Tiên', 'Huyện', 68);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (688, 'Phước Long', 'Thị xã', 70);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (689, 'Đồng Xoài', 'Thị xã', 70);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (690, 'Bình Long', 'Thị xã', 70);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (691, 'Bù Gia Mập', 'Huyện', 70);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (692, 'Lộc Ninh', 'Huyện', 70);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (693, 'Bù Đốp', 'Huyện', 70);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (694, 'Hớn Quản', 'Huyện', 70);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (695, 'Đồng Phú', 'Huyện', 70);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (696, 'Bù Đăng', 'Huyện', 70);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (697, 'Chơn Thành', 'Huyện', 70);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (698, 'Phú Riềng', 'Huyện', 70);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (703, 'Tây Ninh', 'Thành phố', 72);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (705, 'Tân Biên', 'Huyện', 72);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (706, 'Tân Châu', 'Huyện', 72);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (707, 'Dương Minh Châu', 'Huyện', 72);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (708, 'Châu Thành', 'Huyện', 72);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (709, 'Hòa Thành', 'Huyện', 72);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (710, 'Gò Dầu', 'Huyện', 72);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (711, 'Bến Cầu', 'Huyện', 72);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (712, 'Trảng Bàng', 'Huyện', 72);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (718, 'Thủ Dầu Một', 'Thành phố', 74);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (719, 'Bàu Bàng', 'Huyện', 74);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (720, 'Dầu Tiếng', 'Huyện', 74);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (721, 'Bến Cát', 'Thị xã', 74);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (722, 'Phú Giáo', 'Huyện', 74);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (723, 'Tân Uyên', 'Thị xã', 74);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (724, 'Dĩ An', 'Thị xã', 74);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (725, 'Thuận An', 'Thị xã', 74);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (726, 'Bắc Tân Uyên', 'Huyện', 74);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (731, 'Biên Hòa', 'Thành phố', 75);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (732, 'Long Khánh', 'Thị xã', 75);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (734, 'Tân Phú', 'Huyện', 75);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (735, 'Vĩnh Cửu', 'Huyện', 75);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (736, 'Định Quán', 'Huyện', 75);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (737, 'Trảng Bom', 'Huyện', 75);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (738, 'Thống Nhất', 'Huyện', 75);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (739, 'Cẩm Mỹ', 'Huyện', 75);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (740, 'Long Thành', 'Huyện', 75);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (741, 'Xuân Lộc', 'Huyện', 75);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (742, 'Nhơn Trạch', 'Huyện', 75);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (747, 'Vũng Tàu', 'Thành phố', 77);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (748, 'Bà Rịa', 'Thành phố', 77);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (750, 'Châu Đức', 'Huyện', 77);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (751, 'Xuyên Mộc', 'Huyện', 77);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (752, 'Long Điền', 'Huyện', 77);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (753, 'Đất Đỏ', 'Huyện', 77);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (754, 'Tân Thành', 'Huyện', 77);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (755, 'Côn Đảo', 'Huyện', 77);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (760, '1', 'Quận', 79);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (761, '12', 'Quận', 79);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (762, 'Thủ Đức', 'Quận', 79);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (763, '9', 'Quận', 79);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (764, 'Gò Vấp', 'Quận', 79);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (765, 'Bình Thạnh', 'Quận', 79);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (766, 'Tân Bình', 'Quận', 79);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (767, 'Tân Phú', 'Quận', 79);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (768, 'Phú Nhuận', 'Quận', 79);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (769, '2', 'Quận', 79);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (770, '3', 'Quận', 79);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (771, '10', 'Quận', 79);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (772, '11', 'Quận', 79);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (773, '4', 'Quận', 79);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (774, '5', 'Quận', 79);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (775, '6', 'Quận', 79);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (776, '8', 'Quận', 79);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (777, 'Bình Tân', 'Quận', 79);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (778, '7', 'Quận', 79);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (783, 'Củ Chi', 'Huyện', 79);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (784, 'Hóc Môn', 'Huyện', 79);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (785, 'Bình Chánh', 'Huyện', 79);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (786, 'Nhà Bè', 'Huyện', 79);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (787, 'Cần Giờ', 'Huyện', 79);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (794, 'Tân An', 'Thành phố', 80);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (795, 'Kiến Tường', 'Thị xã', 80);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (796, 'Tân Hưng', 'Huyện', 80);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (797, 'Vĩnh Hưng', 'Huyện', 80);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (798, 'Mộc Hóa', 'Huyện', 80);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (799, 'Tân Thạnh', 'Huyện', 80);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (800, 'Thạnh Hóa', 'Huyện', 80);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (801, 'Đức Huệ', 'Huyện', 80);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (802, 'Đức Hòa', 'Huyện', 80);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (803, 'Bến Lức', 'Huyện', 80);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (804, 'Thủ Thừa', 'Huyện', 80);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (805, 'Tân Trụ', 'Huyện', 80);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (806, 'Cần Đước', 'Huyện', 80);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (807, 'Cần Giuộc', 'Huyện', 80);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (808, 'Châu Thành', 'Huyện', 80);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (815, 'Mỹ Tho', 'Thành phố', 82);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (816, 'Gò Công', 'Thị xã', 82);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (817, 'Cai Lậy', 'Huyện', 82);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (818, 'Tân Phước', 'Huyện', 82);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (819, 'Cái Bè', 'Huyện', 82);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (820, 'Cai Lậy', 'Thị xã', 82);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (821, 'Châu Thành', 'Huyện', 82);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (822, 'Chợ Gạo', 'Huyện', 82);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (823, 'Gò Công Tây', 'Huyện', 82);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (824, 'Gò Công Đông', 'Huyện', 82);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (825, 'Tân Phú Đông', 'Huyện', 82);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (829, 'Bến Tre', 'Thành phố', 83);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (831, 'Châu Thành', 'Huyện', 83);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (832, 'Chợ Lách', 'Huyện', 83);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (833, 'Mỏ Cày Nam', 'Huyện', 83);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (834, 'Giồng Trôm', 'Huyện', 83);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (835, 'Bình Đại', 'Huyện', 83);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (836, 'Ba Tri', 'Huyện', 83);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (837, 'Thạnh Phú', 'Huyện', 83);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (838, 'Mỏ Cày Bắc', 'Huyện', 83);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (842, 'Trà Vinh', 'Thành phố', 84);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (844, 'Càng Long', 'Huyện', 84);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (845, 'Cầu Kè', 'Huyện', 84);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (846, 'Tiểu Cần', 'Huyện', 84);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (847, 'Châu Thành', 'Huyện', 84);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (848, 'Cầu Ngang', 'Huyện', 84);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (849, 'Trà Cú', 'Huyện', 84);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (850, 'Duyên Hải', 'Huyện', 84);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (851, 'Duyên Hải', 'Thị xã', 84);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (855, 'Vĩnh Long', 'Thành phố', 86);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (857, 'Long Hồ', 'Huyện', 86);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (858, 'Mang Thít', 'Huyện', 86);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (859, ' Vũng Liêm', 'Huyện', 86);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (860, 'Tam Bình', 'Huyện', 86);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (861, 'Bình Minh', 'Thị xã', 86);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (862, 'Trà Ôn', 'Huyện', 86);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (863, 'Bình Tân', 'Huyện', 86);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (866, 'Cao Lãnh', 'Thành phố', 87);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (867, 'Sa Đéc', 'Thành phố', 87);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (868, 'Hồng Ngự', 'Thị xã', 87);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (869, 'Tân Hồng', 'Huyện', 87);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (870, 'Hồng Ngự', 'Huyện', 87);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (871, 'Tam Nông', 'Huyện', 87);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (872, 'Tháp Mười', 'Huyện', 87);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (873, 'Cao Lãnh', 'Huyện', 87);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (874, 'Thanh Bình', 'Huyện', 87);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (875, 'Lấp Vò', 'Huyện', 87);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (876, 'Lai Vung', 'Huyện', 87);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (877, 'Châu Thành', 'Huyện', 87);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (883, 'Long Xuyên', 'Thành phố', 89);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (884, 'Châu Đốc', 'Thành phố', 89);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (886, 'An Phú', 'Huyện', 89);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (887, 'Tân Châu', 'Thị xã', 89);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (888, 'Phú Tân', 'Huyện', 89);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (889, 'Châu Phú', 'Huyện', 89);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (890, 'Tịnh Biên', 'Huyện', 89);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (891, 'Tri Tôn', 'Huyện', 89);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (892, 'Châu Thành', 'Huyện', 89);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (893, 'Chợ Mới', 'Huyện', 89);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (894, 'Thoại Sơn', 'Huyện', 89);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (899, 'Rạch Giá', 'Thành phố', 91);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (900, 'Hà Tiên', 'Thị xã', 91);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (902, 'Kiên Lương', 'Huyện', 91);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (903, 'Hòn Đất', 'Huyện', 91);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (904, 'Tân Hiệp', 'Huyện', 91);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (905, 'Châu Thành', 'Huyện', 91);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (906, 'Giồng Riềng', 'Huyện', 91);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (907, 'Gò Quao', 'Huyện', 91);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (908, 'An Biên', 'Huyện', 91);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (909, 'An Minh', 'Huyện', 91);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (910, 'Vĩnh Thuận', 'Huyện', 91);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (911, 'Phú Quốc', 'Huyện', 91);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (912, 'Kiên Hải', 'Huyện', 91);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (913, 'U Minh Thượng', 'Huyện', 91);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (914, 'Giang Thành', 'Huyện', 91);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (916, 'Ninh Kiều', 'Quận', 92);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (917, 'Ô Môn', 'Quận', 92);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (918, 'Bình Thuỷ', 'Quận', 92);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (919, 'Cái Răng', 'Quận', 92);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (923, 'Thốt Nốt', 'Quận', 92);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (924, 'Vĩnh Thạnh', 'Huyện', 92);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (925, 'Cờ Đỏ', 'Huyện', 92);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (926, 'Phong Điền', 'Huyện', 92);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (927, 'Thới Lai', 'Huyện', 92);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (930, 'Vị Thanh', 'Thành phố', 93);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (931, 'Ngã Bảy', 'Thị xã', 93);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (932, 'Châu Thành A', 'Huyện', 93);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (933, 'Châu Thành', 'Huyện', 93);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (934, 'Phụng Hiệp', 'Huyện', 93);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (935, 'Vị Thuỷ', 'Huyện', 93);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (936, 'Long Mỹ', 'Huyện', 93);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (937, 'Long Mỹ', 'Thị xã', 93);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (941, 'Sóc Trăng', 'Thành phố', 94);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (942, 'Châu Thành', 'Huyện', 94);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (943, 'Kế Sách', 'Huyện', 94);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (944, 'Mỹ Tú', 'Huyện', 94);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (945, 'Cù Lao Dung', 'Huyện', 94);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (946, 'Long Phú', 'Huyện', 94);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (947, 'Mỹ Xuyên', 'Huyện', 94);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (948, 'Ngã Năm', 'Thị xã', 94);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (949, 'Thạnh Trị', 'Huyện', 94);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (950, 'Vĩnh Châu', 'Thị xã', 94);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (951, 'Trần Đề', 'Huyện', 94);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (954, 'Bạc Liêu', 'Thành phố', 95);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (956, 'Hồng Dân', 'Huyện', 95);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (957, 'Phước Long', 'Huyện', 95);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (958, 'Vĩnh Lợi', 'Huyện', 95);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (959, 'Giá Rai', 'Thị xã', 95);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (960, 'Đông Hải', 'Huyện', 95);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (961, 'Hoà Bình', 'Huyện', 95);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (964, 'Cà Mau', 'Thành phố', 96);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (966, 'U Minh', 'Huyện', 96);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (967, 'Thới Bình', 'Huyện', 96);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (968, 'Trần Văn Thời', 'Huyện', 96);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (969, 'Cái Nước', 'Huyện', 96);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (970, 'Đầm Dơi', 'Huyện', 96);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (971, 'Năm Căn', 'Huyện', 96);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (972, 'Phú Tân', 'Huyện', 96);
INSERT INTO public.district (id, district_name, district_type, province_id) VALUES (973, 'Ngọc Hiển', 'Huyện', 96);
